# ========================================
# CI/CD Deploy to DigitalOcean via SSH + Docker
# ========================================

name: CI/CD Deploy to DigitalOcean

# Trigger this workflow every time code is pushed to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted Linux runner

    steps:
      # Step 1: Clone your GitHub repository into the runner
      - name: 📥 Checkout source code
        uses: actions/checkout@v3

      # Step 2: Securely copy the project files to your DigitalOcean server using SCP
      - name: 📦 Copy files to DigitalOcean server
        uses: appleboy/scp-action@master
        with:
          host: 206.189.239.195                        # Your Droplet's public IP
          username: root                               # User to connect as (usually root)
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}       # SSH private key stored in GitHub Secrets
          source: "."                                  # Local files to copy
          target: "/root/occ_odoo17_docker"            # Target folder on the remote server

      # Step 3: Fix filestore permissions & Restart Docker containers on the server
      - name: 🔁 Fix permissions and restart containers
        uses: appleboy/ssh-action@master
        with:
          host: 206.189.239.195
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            echo "📂 Fixing filestore permissions..."
            cd /root/occ_odoo17_docker

            # Ensure the filestore directory is writable by the Odoo container (UID 1000)
            chown -R 1000:1000 ./filestore
            chmod -R 777 ./filestore

            echo "🧹 Cleaning up existing containers if they exist..."
            docker rm -f occ-odoo17 occ-odoo17-db occ-tomcat || true

            echo "🚀 Rebuilding and starting containers..."
            docker-compose up -d --build