# ========================================
# CI/CD Deploy to DigitalOcean via SSH + Docker (Conditional)
# ========================================

name: CI/CD Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------------
      # 1) Check out the code
      # -----------------------------------
      - name: 📥 Checkout source code
        uses: actions/checkout@v3

      # -----------------------------------
      # 2) Determine which files changed
      # -----------------------------------
      - name: 🔎 Determine changed files
        id: changes
        run: |
          # Compare last commit to the one before it
          DOCKER_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep -E "docker-compose\.yml|Dockerfile|tomcat/" || true)
          CUSTOM_ADDONS_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep -E "odoo/addons/custom" || true)

          # Set GitHub Actions env variables
          if [ -n "$DOCKER_CHANGED" ]; then
            echo "docker_changed=true" >> $GITHUB_ENV
          else
            echo "docker_changed=false" >> $GITHUB_ENV
          fi

          if [ -n "$CUSTOM_ADDONS_CHANGED" ]; then
            echo "custom_addons_changed=true" >> $GITHUB_ENV
          else
            echo "custom_addons_changed=false" >> $GITHUB_ENV
          fi

      # -----------------------------------
      # 3) Securely copy files to DigitalOcean
      # -----------------------------------
      - name: 📦 Copy files to DigitalOcean server
        uses: appleboy/scp-action@master
        with:
          host: 206.189.239.195
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          source: "."
          target: "/root/occ_odoo17_docker"

      # -----------------------------------
      # 4) SSH into server and do conditional deploy
      # -----------------------------------
      - name: 🔁 Conditional Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: 206.189.239.195
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            echo "📂 Fixing filestore permissions..."
            cd /root/occ_odoo17_docker
            mkdir -p ./filestore
            chown -R 1000:1000 ./filestore
            chmod -R 777 ./filestore

            # Read the environment variables we set in the previous step
            if [ "${{ env.docker_changed }}" = "true" ]; then
              echo "🚀 Docker-related changes found → Full rebuild!"
              docker-compose down -v
              docker-compose up -d --build
            elif [ "${{ env.custom_addons_changed }}" = "true" ]; then
              echo "♻️ Only custom addons changed → Partial Odoo module update!"
              # Adjust container name & DB name to your environment
              docker exec -it occ-odoo17-web odoo -d OCC_Payroll_test01 -u all --stop-after-init
              docker restart occ-odoo17-web
            else
              echo "✅ No changes requiring container restart. Done!"
            fi